### ISSUE TITLE
support for JsonFilter with specific filterId?

### ISSUE THREAD

**Issue by krishna81m** [FasterXML/jackson-module-afterburner#61]
Does after burner support JsonFilter, say, generate bytecode based on specific filterId? This needs custom logic based on filter.

I tested using filters with and without afterburner and so no change in performance, the only way I could confirm the module existed is by checking that the module is registered in the object mapper, is there a better way if there is optimization or not?

`http://wiki.fasterxml.com/JacksonFeatureJsonFilter`
Or Spring way of doing it:
`MappingJacksonValue jacksonValue = new MappingJacksonValue(response);
jacksonValue.setFilters(customfilter);`

wiki links don't work.

**Comment by cowtowncoder** [comment]
Afterburner only optimizes calls that `jackson-databind` makes using reflection, as well as simplifies serialization/deserialization of a small number of standard types (strings, numbers).
Only minimum amount of bytecode is generated to basically replace access to getters, setters and constructors. Nothing more complicated than that is being done or planned to be implemented.

JsonFilter should be used the same way as default `jackson-databind` does it. So filtering itself should work as before; if not, that is a bug.

**Comment by krishna81m** [comment]
The wiki links did not work and I could find any benchmarks to verify the 10%-30% gains. 

As expected, filters did not show any difference, however, without the filters, I did see improvements, thanks.

Spring 4.2 	#Threads #Throughput	#ResponseTime (ms)
no filtering	10 		 1400			5-6
no filtering	100           1881			42-43
no filtering	1000         1805			450-490
				
Spring 4.2 
no filtering                #Threads #Throughput	#ResponseTime (ms)
with afterburner	10 	    1420		5
with afterburner	100      1950		38-39
with afterburner	1000    1930- 		400-440

Spring 4.2 MappingJacksonValue
setFilters+                #Threads #Throughput	#ResponseTime (ms)
module-afterburner	10		1512		4-5
module-afterburner	100		1836		42-40
module-afterburner	1000        1900		400-460

**Comment by cowtowncoder** [comment]
@krishna81m Jackson does not use any logging, by design. I don't like libraries (as opposed to frameworks or app code) doing their own logging, for multiple reasons, so no logging is likely to be added. But I am open to adding diagnostic interfaces/extensions where they make sense

For profiling I use

https://github.com/FasterXML/jackson-benchmarks

although `jvm-serializers` also does have afterburner-enabled versions. Neither uses filters or most any other advanced features; Afterburner only optimizes "vanilla" cases.

But as JSON Filters, it may be that optimizations are not enabled even if they perhaps could be: the main rule in enabling generation of accessors has been "first do no harm", meaning that serializers/deserializers that are likely to either be problematic (like custom (de)serializers), or unlikely to benefit, will not be changed by Afterburner.
However I do not think use of JSON Views or JSON Filters should prevent improvements necessarily, since both use delegation model.
